"""add account status, machines and lead service specs

Revision ID: d12b7d529a25
Revises: d6eae60d1668
Create Date: 2026-07-15 11:01:53.582836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd12b7d529a25'
down_revision: Union[str, None] = 'd6eae60d1668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_serial_number'), ['serial_number'], unique=False)

    # server_default manual: colunas NOT NULL novas em tabelas com dados existentes
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PROSPECT', 'ACTIVE', 'INACTIVE', name='accountstatus', native_enum=False, length=10), nullable=False, server_default='PROSPECT'))
        batch_op.create_index(batch_op.f('ix_accounts_status'), ['status'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('printer_type', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('it_product', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('it_quantity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('it_specs', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('it_specs')
        batch_op.drop_column('it_quantity')
        batch_op.drop_column('it_product')
        batch_op.drop_column('printer_type')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_serial_number'))
        batch_op.drop_index(batch_op.f('ix_machines_account_id'))

    op.drop_table('machines')
    # ### end Alembic commands ###
