"""add printer rental and it outsourcing domain fields

Revision ID: d6eae60d1668
Revises: 1d67d9fe0df0
Create Date: 2026-07-03 10:34:07.891902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6eae60d1668'
down_revision: Union[str, None] = '1d67d9fe0df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default é necessário para adicionar colunas NOT NULL em tabelas com dados
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False, server_default=''))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('interest', sa.Enum('PRINTER_RENTAL', 'IT_OUTSOURCING', 'BOTH', name='leadinterest', native_enum=False, length=20), nullable=False, server_default='PRINTER_RENTAL'))
        batch_op.add_column(sa.Column('current_provider', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('contract_renewal', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('printer_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('monthly_volume_mono', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('monthly_volume_color', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_leads_contract_renewal'), ['contract_renewal'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.Enum('PRINTER_RENTAL', 'IT_OUTSOURCING', 'MIXED', name='servicetype', native_enum=False, length=20), nullable=False, server_default='PRINTER_RENTAL'))
        batch_op.add_column(sa.Column('billing_type', sa.Enum('MONTHLY', 'ONE_TIME', name='billingtype', native_enum=False, length=10), nullable=False, server_default='MONTHLY'))
        batch_op.add_column(sa.Column('contract_months', sa.Integer(), nullable=False, server_default='12'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('contract_months')
        batch_op.drop_column('billing_type')
        batch_op.drop_column('service_type')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_contract_renewal'))
        batch_op.drop_column('monthly_volume_color')
        batch_op.drop_column('monthly_volume_mono')
        batch_op.drop_column('printer_count')
        batch_op.drop_column('contract_renewal')
        batch_op.drop_column('current_provider')
        batch_op.drop_column('interest')
        batch_op.drop_column('cnpj')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
